cors:
  allowed-origins: ${CORS_ALLOWED_ORIGINS:http://localhost,http://localhost:4200,http://frontend}
server:
  port: ${PORT:8080}
  baseurl: ${BASE_URL:http://localhost}
#  servlet:
#    context-path: /jobs
spring:
  profiles.active: ${SPRING_PROFILES_ACTIVE:secrets}
  jackson:
    property-naming-strategy: SNAKE_CASE
  messages:
    encoding: UTF-8
  web:
    locale: fr
  datasource:
    url: ${SPRING_DATASOURCE_URL:jdbc:postgresql://localhost:5432/dbname}?currentSchema=public
    hikari:
      minimum-idle: 1
      maximum-pool-size: 5
      connection-timeout: 20000
      idle-timeout: 300000
      max-lifetime: 600000
  jpa:
    properties:
      hibernate:
        open-in-view: true
        enable_lazy_load_no_trans: true
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format-sql: true
    show-sql: true
    hibernate:
      ddl-auto: ${SPRING_JPA_HIBERNATE_DDL_AUTO:update}
  mail: 
    properties: 
        mail: 
            smtp: 
                auth: ${SPRING_MAIL_AUTH:true}
                starttls.enable: ${SPRING_MAIL_STARTTLS:true}
