loamok.security.jwt.secret: ${JWT_SECRET:VGhpc0lzQURldkp3dFNlY3JldEZvckxvY2FsVGVzdGluZ09ubHkxMjM0NQ==}
spring:
  datasource:
    username: ${SPRING_DATASOURCE_USERNAME:dbuser}
    password: ${SPRING_DATASOURCE_PASSWORD:dbuserp@ssw0rd}
  mail:
    host: ${SPRING_MAIL_HOST:mailer}
    port: ${SPRING_MAIL_PORT:1025}
    username: ${SPRING_MAIL_USER:demo@example.com}
    password: ${SPRING_MAIL_PASS:MailerP@ssw0rd}
