loamok:
  emails:
    email:
      base-url: ${BASE_URL:http://localhost}
      admin-email: ${ADMIN_EMAIL:admin@example.com}
      application-name: Jobs
  security:
    email:
      key-validity-hours: 1
    jwt:
      access-token-expiration-hours: 24
      remember-me-token-expiration-days: 365
      stored-token-expiration-hours: 2
    cors:
      allowed-origins: ${CORS_ORIGINS:http://localhost:4200,http://localhost:8090}
      allowed-methods: GET,POST,PUT,PATCH,DELETE,OPTIONS
      allowed-headers: "*"
      allow-credentials: true
      max-age: 3600
    endpoints:
      auth-base-path: /authorize
      register-base-path: /register
      enable-request-logging: false

springdoc:
  api-docs:
    enabled: ${SPRINGDOC_ENABLED:false}
  swagger-ui:
    enabled: ${SPRINGDOC_ENABLED:false}
spring:
  profiles.active: ${SPRING_PROFILES_ACTIVE:dev,secrets}
  jackson:
    property-naming-strategy: SNAKE_CASE
  messages:
    encoding: UTF-8
  web:
    locale: fr
  datasource:
    url: ${SPRING_DATASOURCE_URL:jdbc:postgresql://localhost:5432/dbname}?currentSchema=public
    hikari:
      minimum-idle: 1
      maximum-pool-size: 5
      connection-timeout: 20000
      idle-timeout: 300000
      max-lifetime: 600000
  jpa:
    properties:
      hibernate:
        open-in-view: false
        enable_lazy_load_no_trans: true
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format-sql: true
    show-sql: true
    hibernate:
      ddl-auto: ${SPRING_JPA_HIBERNATE_DDL_AUTO:update}
  mail: 
    properties: 
        mail: 
            smtp: 
                auth: ${SPRING_MAIL_AUTH:true}
                starttls.enable: ${SPRING_MAIL_STARTTLS:true}
